# GHC 9.4.7
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-21.19

packages:
- .

extra-deps:
- levenshtein-0.2.1.0

nix:
  packages: [zlib]
