# GHC 8.10.7
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-18.28

packages:
- .

extra-deps:
- nvim-hs-2.3.0.0
- template-haskell-compat-v0208-0.1.9.1
- levenshtein-0.1.3.0

nix:
  packages: [zlib]
