# GHC 9.4.6
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-21.9

packages:
- .

extra-deps:
- levenshtein-0.2.1.0

nix:
  packages: [zlib]
