# GHC 9.2.8
# Update `defaultGHCVersion` in `./flake.nix` when updating to resolver with different GHC version.
resolver: lts-20.25

packages:
- .

extra-deps:
- diff-loc-0.1.0.0
- levenshtein-0.2.1.0

# TODO: Remove when updating to LTS that includes `nvim-hs` version >= 2.3.2.2.
- git: https://github.com/neovimhaskell/nvim-hs.git
  commit: eaf826d4156b0281ef7ce9dec35ba720b5c45f09

nix:
  packages: [zlib]
