name: Cache Stack dirs
description: Cache Stack related directories for faster builds

inputs:
  stack-work-dir:
    description: Path to project local Stack cache
    required: false
    default: .stack-work
  key-always-unique:
    description: Whether always make the cache key unique
    required: false
    default: "false"

runs:
  using: "composite"

  steps:
    - name: Setup required variables
      shell: bash
      run: |
        if [ $RUNNER_OS = "Windows" ]; then
          echo "global_stack_dir=~\AppData\Roaming\stack" >> $GITHUB_ENV
        else
          echo "global_stack_dir=~/.stack" >> $GITHUB_ENV
        fi

        if [ "${{ inputs.key-always-unique }}" == "true" ]; then
          echo "unique_suffix=-$(date '+%s')" >> $GITHUB_ENV
        else
          echo "unique_suffix=" >> $GITHUB_ENV
        fi

    - name: Cache ${{ env.global_stack_dir }}
      uses: actions/cache@v3
      with:
        path: ${{ env.global_stack_dir }}
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}${{ env.unique_suffix }}
        restore-keys: |
          ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-
          ${{ runner.os }}-stack-global-

    - name: Cache ${{ inputs.stack-work-dir }}
      uses: actions/cache@v3
      with:
        path: ${{ inputs.stack-work-dir }}
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}${{ env.unique_suffix }}
        restore-keys: |
          ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-
          ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-
          ${{ runner.os }}-stack-work-
