name: Nix Agda CI

on:
  push:
    paths:
      - flake.*
      - .github/workflows/nix-agda.yml
  pull_request:
    paths:
      - flake.*
      - .github/workflows/nix-agda.yml
    branches: [ master ]

jobs:
  build-agda:
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-12', 'ubuntu-22.04']

    name: Nix Agda
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build Agda
        run: |
          nix -L build .#agda
