name: Nix CI

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build-package:
    strategy:
      fail-fast: false
      matrix:
        # Keep in sync with `ghcVersions` in `../../flake.nix`.
        ghc: ['810', '92', '94', '96']

    name: Build package (ghc${{ matrix.ghc }})
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Build cornelis
        run: |
          nix -L build .#cornelis-ghc${{ matrix.ghc }}

  build-vim-plugin:
    name: Build Vim plugin
    runs-on: ${{ inputs.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build cornelis Vim plugin
        run: |
          nix -L build .#cornelis-vim

